version: 2
updates:
- package-ecosystem: npm
  directory: "/{{cookiecutter.project_slug}}/frontend"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
- package-ecosystem: pip
  directory: "/{{cookiecutter.project_slug}}/backend"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: httpx
    versions:
    - 0.16.1
